apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xkjcygu7u-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-dbe58f1f97.30ql.p3.openshiftapps.com/rhtap/rhtap-qe:6b9b2abbd96f8f8a0f61c0d9d9d2afe598dfb6da@sha256:976dc4fd48fdb2c1646891818526ce8e1bc1bf3aa8a0b6bde33d3de8ef7bcaa7
          name: container-image
